/** Tailwind class bundles for expanded sections — each template gets distinct section + FAB styling */

export const expandableThemeT1 = {
  maxW: 'max-w-[1100px]',
  stickyHeader: 'bg-[#fbf7f1]/95 border-b border-black/5 backdrop-blur',
  brandClass: 'text-[18px] font-extrabold tracking-wide text-black',
  navLink: 'text-[12px] font-semibold text-black/70 hover:text-black',
  loginBtn:
    'hidden h-[28px] items-center justify-center rounded-[6px] border border-black/15 bg-white px-4 text-[12px] font-semibold text-black/70 shadow-[0px_10px_24px_rgba(0,0,0,0.06)] sm:inline-flex',
  signupBtn:
    'hidden h-[28px] items-center justify-center rounded-[6px] bg-black px-4 text-[12px] font-semibold text-white sm:inline-flex',
  sectionTitle: 'text-center text-[18px] font-extrabold text-[#1b2342]',
  bodyMuted: 'text-[11px] font-medium text-black/45',
  card: 'rounded-[18px] bg-white shadow-[0px_12px_26px_rgba(0,0,0,0.08)] ring-1 ring-black/5',
  altBand: 'bg-[#fbf7f1]',
  offersSection: 'bg-[#fbf7f1]',
  catalogueSection: 'bg-white',
  contactSection: 'bg-[#f5d9b7]/30',
  mapSection: 'bg-[#fbf7f1]',
  socialSection: 'bg-white border-y border-[#e86c5a]/15',
  hoursSection: 'bg-[#f8f3eb]',
  testimonialsSection: 'bg-white',
  feedSection: 'bg-[#fbf7f1]',
  offersGrid: 'gap-5',
  catalogueGrid: 'gap-5',
  feedGrid: 'gap-5',
  offerCard: 'border border-[#f0a12b]/20',
  catalogueCard: 'transition-colors hover:ring-2 hover:ring-[#1b2342]/10',
  feedCard: 'border-l-4 border-[#f0a12b] pl-1',
  offersTitleExtra: 'font-[Georgia,serif] tracking-wide',
  catalogueTitleExtra: 'font-[Georgia,serif]',
  mapTitleExtra: 'font-[Georgia,serif]',
  feedTitleExtra: 'font-[Georgia,serif]',
  hoursTitleExtra: 'font-[Georgia,serif]',
  testimonialsTitleExtra: '',
  offerTag: 'bg-black text-white',
  priceAccent: 'text-black font-extrabold',
  linkAccent: 'text-[12px] font-bold text-[#f0a12b] underline-offset-2 hover:underline',
  socialBand: 'bg-[#fbf7f1]',
  socialHeading: 'text-center font-[Georgia,serif] text-[18px] font-extrabold text-[#1b2342]',
  socialSubtitle: 'text-[11px] font-medium text-black/45',
  socialBtn: 'rounded-full border-2 border-black/15 px-4 py-2 text-[11px] font-bold text-black hover:bg-white',
  hoursBand: 'bg-white',
  hoursRow: 'border-[#1b2342]/10',
  hoursList: '',
  testimonialBand: 'bg-[#fbf7f1]',
  testimonialCarouselLayout: '',
  testimonialSpotlight: '',
  reviewCard: 'rounded-[18px] bg-white p-5 shadow-[0px_12px_26px_rgba(0,0,0,0.08)] ring-1 ring-black/5',
  reviewList: '',
  reviewListCard: '',
  reviewFormCard: '',
  reviewForm: '',
  submitBtn: 'h-[44px] w-full rounded-[8px] bg-black text-[11px] font-bold text-white',
  contactFormBtn:
    'h-[40px] w-full rounded-[8px] bg-[#f0a12b] text-[11px] font-bold text-white shadow-[0px_10px_24px_rgba(240,161,43,0.35)]',
  cardTitle: 'font-[Georgia,serif] text-[13px] font-extrabold text-[#1b2342]',
  contactHeading: 'font-[Georgia,serif] text-[17px] font-extrabold text-[#1b2342]',
  contactListItem: '',
  contactGrid: '',
  contactDetailsWrap: '',
  contactFormWrap: '',
  contactForm: '',
  input:
    'h-[40px] rounded-[8px] border border-[#1b2342]/12 bg-white px-3 text-[12px] outline-none focus:ring-2 focus:ring-[#f0a12b]/25',
  textarea:
    'min-h-[100px] rounded-[8px] border border-[#1b2342]/12 bg-white px-3 py-2 text-[12px] outline-none focus:ring-2 focus:ring-[#f0a12b]/25',
  mapContainer:
    'mt-6 aspect-[16/9] overflow-hidden rounded-[24px] ring-2 ring-[#f0a12b]/20 shadow-[0px_20px_48px_rgba(27,35,66,0.08)] sm:aspect-[21/9]',
  carouselBtn:
    'grid size-10 place-items-center rounded-full border border-[#1b2342]/10 bg-white text-lg text-[#1b2342]/45 shadow-sm hover:bg-[#fbf7f1]',
  testimonialTitle: 'text-left font-[Georgia,serif] text-[18px] font-extrabold text-[#1b2342] sm:text-[22px]',
  reviewFormTitle: 'font-[Georgia,serif] text-[14px] font-extrabold text-[#1b2342]',
  reviewAuthor: 'text-[12px] font-extrabold text-[#1b2342]',
  reviewRatingLabel: 'text-black/50',
  starActive: 'text-[#f0a12b]',
  starEmpty: 'text-[#1b2342]/15',
  dateMeta: 'text-[9px] font-bold uppercase tracking-wider text-[#e78b77]/80',
  feedDate: '',
  hoursDay: 'text-[#1b2342]/50',
  hoursValue: 'text-[#1b2342]',
  hoursInner: '',
  avatarRing: 'ring-2 ring-[#f0a12b]/35',
  reviewsGrid: '',
  fabOutline: 'border-2 border-[#1b2342]/20 bg-white text-[#1b2342]',
  fabFill: 'bg-[#1b2342] text-white',
  fabFill2: 'bg-[#f0a12b] text-white',
  fabShell:
    'grid size-12 place-items-center rounded-2xl text-[18px] shadow-[0px_14px_34px_rgba(27,35,66,0.18)] ring-1 ring-[#1b2342]/10 sm:size-14',
  fabHint:
    'rounded-[12px] bg-[#fbf7f1] px-3 py-2 text-[11px] font-semibold text-[#1b2342] shadow-lg ring-1 ring-[#f0a12b]/25',
  mobileNavBg: 'bg-[#fbf7f1]',
}

export const expandableThemeT2 = {
  maxW: 'max-w-[980px]',
  stickyHeader: 'bg-[#eef6ee]/95 border-b border-black/5 backdrop-blur',
  brandClass: 'text-[14px] font-extrabold text-[#1a1c19]',
  navLink: 'text-[11px] font-semibold text-black/60 hover:text-black',
  loginBtn:
    'hidden h-[32px] items-center justify-center rounded-[999px] border border-black/10 bg-white px-4 text-[11px] font-semibold text-black/70 sm:inline-flex',
  signupBtn:
    'hidden h-[32px] items-center justify-center rounded-[999px] bg-[#2d7a49] px-4 text-[11px] font-semibold text-white sm:inline-flex',
  sectionTitle: 'text-center text-[13px] font-extrabold text-[#1a1c19]',
  bodyMuted: 'text-[10px] font-medium text-black/45',
  card: 'rounded-[16px] bg-white shadow-[0px_12px_26px_rgba(0,0,0,0.10)]',
  altBand: 'bg-[#dff1df]',
  offersSection: 'bg-[#c8e6c9]/35',
  catalogueSection: 'bg-white',
  contactSection: 'bg-[#dff1df]',
  mapSection: 'bg-[#eef6ee]',
  socialSection: 'bg-[#2d7a49] text-white',
  hoursSection: 'bg-[#dff1df]',
  testimonialsSection: 'bg-white',
  feedSection: 'bg-[#eef6ee]',
  offersGrid: '',
  catalogueGrid: '',
  feedGrid: '',
  offerCard: 'ring-1 ring-[#2d7a49]/10',
  catalogueCard: '',
  feedCard: 'border-t-4 border-[#2d7a49]',
  offersTitleExtra: '',
  catalogueTitleExtra: '',
  mapTitleExtra: '',
  feedTitleExtra: '',
  hoursTitleExtra: '',
  testimonialsTitleExtra: '',
  offerTag: 'bg-[#2d7a49] text-white',
  priceAccent: 'text-[#2d7a49] font-extrabold',
  linkAccent: 'text-[11px] font-bold text-[#2d7a49]',
  socialBand: 'bg-[#dff1df]',
  socialHeading: 'text-center text-[13px] font-extrabold text-white',
  socialSubtitle: 'text-[10px] font-medium text-white/80',
  socialBtn:
    'rounded-full border-2 border-white/40 bg-transparent px-4 py-2 text-[10px] font-bold text-white hover:bg-white hover:text-[#2d7a49]',
  hoursBand: 'bg-[#dff1df]',
  hoursRow: 'border-[#2d7a49]/15',
  hoursList: '',
  testimonialBand: 'bg-[#eef6ee]',
  testimonialCarouselLayout: '',
  testimonialSpotlight: '',
  reviewCard: 'rounded-[16px] bg-white p-4 shadow-[0px_12px_26px_rgba(0,0,0,0.10)]',
  reviewList: '',
  reviewListCard: '',
  reviewFormCard: 'ring-1 ring-[#2d7a49]/12',
  reviewForm: '',
  submitBtn: 'h-[40px] w-full rounded-[999px] bg-[#2d7a49] text-[10px] font-bold text-white',
  contactFormBtn: 'h-[40px] w-full rounded-[999px] bg-[#2d7a49] text-[10px] font-bold text-white',
  cardTitle: 'text-[13px] font-extrabold text-[#1a1c19]',
  contactHeading: 'text-[15px] font-extrabold text-[#2d7a49]',
  contactListItem: '',
  contactGrid: '',
  contactDetailsWrap: '',
  contactFormWrap: 'rounded-[16px] bg-white/80 p-4 ring-1 ring-[#2d7a49]/10',
  contactForm: '',
  input:
    'h-[40px] rounded-full border border-[#2d7a49]/20 bg-white px-4 text-[12px] outline-none focus:ring-2 focus:ring-[#2d7a49]/25',
  textarea:
    'min-h-[100px] rounded-[20px] border border-[#2d7a49]/20 bg-white px-4 py-2 text-[12px] outline-none focus:ring-2 focus:ring-[#2d7a49]/25',
  mapContainer:
    'mt-6 aspect-[16/9] overflow-hidden rounded-[20px] ring-2 ring-[#2d7a49]/15 sm:aspect-[21/9]',
  carouselBtn:
    'grid size-10 place-items-center rounded-full border border-[#2d7a49]/20 bg-white text-lg text-[#2d7a49]',
  testimonialTitle: 'text-left text-[16px] font-extrabold text-[#2d7a49] sm:text-[18px]',
  reviewFormTitle: 'text-[14px] font-extrabold text-[#1a1c19]',
  reviewAuthor: 'text-[12px] font-extrabold text-[#1a1c19]',
  reviewRatingLabel: 'text-[#2d7a49]/70',
  starActive: 'text-[#2d7a49]',
  starEmpty: 'text-black/15',
  dateMeta: 'text-[9px] font-bold uppercase text-[#2d7a49]/70',
  feedDate: '',
  hoursDay: 'text-black/55',
  hoursValue: 'text-[#2d7a49]',
  hoursInner: '',
  avatarRing: 'ring-2 ring-[#2d7a49]/25',
  reviewsGrid: '',
  fabOutline: 'border-2 border-[#2d7a49] bg-white text-[#2d7a49]',
  fabFill: 'bg-[#2d7a49] text-white',
  fabFill2: 'bg-[#1a5c36] text-white',
  fabShell:
    'grid size-12 place-items-center rounded-full text-[18px] shadow-[0px_12px_28px_rgba(45,122,73,0.35)] ring-2 ring-white sm:size-14',
  fabHint: 'rounded-full bg-[#dff1df] px-4 py-2 text-[11px] font-semibold text-[#1a5c36] shadow-lg ring-1 ring-[#2d7a49]/20',
  mobileNavBg: 'bg-[#eef6ee]',
}

export const expandableThemeT3 = {
  maxW: 'max-w-[980px]',
  stickyHeader: 'bg-[#fbefe6]/95 border-b border-black/5 backdrop-blur',
  brandClass: 'text-[14px] font-extrabold text-[#1a1c19]',
  navLink: 'text-[11px] font-semibold text-black/55 hover:text-black',
  loginBtn:
    'hidden h-[32px] items-center justify-center rounded-[999px] bg-white px-4 text-[11px] font-semibold text-black/60 ring-1 ring-black/10 sm:inline-flex',
  signupBtn:
    'hidden h-[32px] items-center justify-center rounded-[999px] bg-[#b8903a] px-4 text-[11px] font-semibold text-white sm:inline-flex',
  sectionTitle: 'text-center text-[20px] font-extrabold text-[#1a1c19]',
  bodyMuted: 'text-[10px] font-medium text-black/35',
  card: 'rounded-[16px] bg-white shadow-[0px_18px_40px_rgba(0,0,0,0.10)] ring-1 ring-black/5',
  altBand: 'bg-[#f6efe6]',
  offersSection: 'bg-[#f6efe6]',
  catalogueSection: 'bg-[#fffdfb]',
  contactSection: 'bg-[#fbefe6]',
  mapSection: 'bg-white',
  socialSection: 'bg-[#f6efe6] border-y border-[#b8903a]/20',
  hoursSection: 'bg-[#fffdfb]',
  testimonialsSection: 'bg-[#fbefe6]',
  feedSection: 'bg-white',
  offersGrid: '',
  catalogueGrid: '',
  feedGrid: '',
  offerCard: 'shadow-[0px_20px_44px_rgba(184,144,58,0.12)]',
  catalogueCard: '',
  feedCard: 'ring-1 ring-[#b8903a]/15',
  offersTitleExtra: '',
  catalogueTitleExtra: '',
  mapTitleExtra: '',
  feedTitleExtra: '',
  hoursTitleExtra: '',
  testimonialsTitleExtra: '',
  offerTag: 'bg-[#b8903a] text-white',
  priceAccent: 'text-[#b8903a] font-extrabold',
  linkAccent: 'text-[11px] font-bold text-[#b8903a]',
  socialBand: 'bg-[#fbefe6]',
  socialHeading: 'text-center text-[20px] font-extrabold text-[#1a1c19]',
  socialSubtitle: 'text-[10px] font-medium text-black/40',
  socialBtn:
    'rounded-full border-2 border-[#b8903a] px-4 py-2 text-[10px] font-bold text-[#b8903a] hover:bg-white',
  hoursBand: 'bg-[#f6efe6]',
  hoursRow: 'border-[#b8903a]/15',
  hoursList: '',
  testimonialBand: 'bg-[#fbefe6]',
  testimonialCarouselLayout: '',
  testimonialSpotlight: 'shadow-[0px_22px_50px_rgba(184,144,58,0.15)]',
  reviewCard: 'rounded-[16px] bg-white p-4 shadow-[0px_18px_40px_rgba(0,0,0,0.08)] ring-1 ring-black/5',
  reviewList: '',
  reviewListCard: '',
  reviewFormCard: '',
  reviewForm: '',
  submitBtn: 'h-[40px] w-full rounded-[999px] bg-[#b8903a] text-[10px] font-bold text-white',
  contactFormBtn: 'h-[40px] w-full rounded-[999px] bg-[#b8903a] text-[10px] font-bold text-white',
  cardTitle: 'text-[14px] font-extrabold text-[#1a1c19]',
  contactHeading: 'text-[19px] font-extrabold text-[#1a1c19]',
  contactListItem: '',
  contactGrid: '',
  contactDetailsWrap: '',
  contactFormWrap: '',
  contactForm: '',
  input:
    'h-[40px] rounded-[12px] border border-[#b8903a]/25 bg-white px-3 text-[12px] outline-none focus:ring-2 focus:ring-[#b8903a]/20',
  textarea:
    'min-h-[100px] rounded-[12px] border border-[#b8903a]/25 bg-white px-3 py-2 text-[12px] outline-none focus:ring-2 focus:ring-[#b8903a]/20',
  mapContainer:
    'mt-6 aspect-[16/9] overflow-hidden rounded-[16px] ring-1 ring-[#b8903a]/35 shadow-[0px_18px_40px_rgba(184,144,58,0.12)] sm:aspect-[21/9]',
  carouselBtn:
    'grid size-10 place-items-center rounded-[12px] border border-[#b8903a]/30 bg-white text-lg text-[#b8903a]',
  testimonialTitle: 'text-left text-[18px] font-extrabold text-[#1a1c19] sm:text-[20px]',
  reviewFormTitle: 'text-[14px] font-extrabold text-[#1a1c19]',
  reviewAuthor: 'text-[12px] font-extrabold text-[#1a1c19]',
  reviewRatingLabel: 'text-black/45',
  starActive: 'text-[#b8903a]',
  starEmpty: 'text-black/15',
  dateMeta: 'text-[9px] font-bold uppercase text-[#b8903a]/80',
  feedDate: '',
  hoursDay: 'text-black/55',
  hoursValue: 'text-[#b8903a]',
  hoursInner: '',
  avatarRing: 'ring-2 ring-[#b8903a]/30',
  reviewsGrid: '',
  fabOutline: 'border-2 border-[#b8903a] bg-white text-[#b8903a]',
  fabFill: 'bg-[#b8903a] text-white',
  fabFill2: 'bg-[#3a59c7] text-white',
  fabShell:
    'grid size-12 place-items-center rounded-2xl text-[18px] shadow-[0px_14px_32px_rgba(184,144,58,0.28)] ring-1 ring-[#b8903a]/25 sm:size-14',
  fabHint: 'rounded-2xl bg-[#fbefe6] px-3 py-2 text-[11px] font-semibold text-[#1a1c19] shadow-lg ring-1 ring-[#b8903a]/25',
  mobileNavBg: 'bg-[#fbefe6]',
}

export const expandableThemeT4 = {
  maxW: 'max-w-[980px]',
  stickyHeader: 'bg-white/95 border-b border-black/5 backdrop-blur',
  brandClass: 'text-[12px] font-extrabold tracking-wide text-black',
  navLink: 'text-[10px] font-semibold text-black/55 hover:text-black',
  loginBtn:
    'hidden h-[32px] items-center justify-center rounded-[8px] border border-black/15 bg-white px-4 text-[10px] font-semibold text-black/70 sm:inline-flex',
  signupBtn:
    'hidden h-[32px] items-center justify-center rounded-[8px] bg-black px-4 text-[10px] font-semibold text-white sm:inline-flex',
  sectionTitle: 'text-center text-[14px] font-extrabold tracking-wide text-black',
  bodyMuted: 'text-[10px] font-medium text-black/45',
  card: 'rounded-[18px] bg-white shadow-[0px_18px_40px_rgba(0,0,0,0.10)] ring-1 ring-black/5',
  altBand: 'bg-[#f4f6f5]',
  offersSection: 'bg-[#f4f6f5]',
  catalogueSection: 'bg-white',
  contactSection: 'bg-[#ebd96b]/35',
  mapSection: 'bg-[#f4f6f5]',
  socialSection: 'bg-black text-white',
  hoursSection: 'bg-white',
  testimonialsSection: 'bg-[#f4f6f5]',
  feedSection: 'bg-white',
  offersGrid: '',
  catalogueGrid: '',
  feedGrid: '',
  offerCard: 'rounded-[8px]',
  catalogueCard: 'rounded-[8px]',
  feedCard: 'rounded-[8px] border-2 border-black',
  offersTitleExtra: 'uppercase tracking-[0.2em]',
  catalogueTitleExtra: 'uppercase tracking-[0.2em]',
  mapTitleExtra: 'uppercase tracking-[0.2em]',
  feedTitleExtra: 'uppercase tracking-[0.2em]',
  hoursTitleExtra: 'uppercase tracking-[0.2em]',
  testimonialsTitleExtra: 'uppercase tracking-[0.15em]',
  offerTag: 'bg-black text-white',
  priceAccent: 'text-black font-extrabold',
  linkAccent: 'text-[10px] font-bold text-black uppercase tracking-wide',
  socialBand: 'bg-[#ebd96b]/40',
  socialHeading: 'text-center text-[14px] font-extrabold tracking-[0.25em] text-white',
  socialSubtitle: 'text-[10px] font-medium text-white/65',
  socialBtn:
    'rounded-none border-2 border-white px-4 py-2 text-[10px] font-bold uppercase tracking-wide text-white hover:bg-[#ebd96b] hover:text-black hover:border-[#ebd96b]',
  hoursBand: 'bg-white',
  hoursRow: 'border-black/15',
  hoursList: '',
  testimonialBand: 'bg-[#f4f6f5]',
  testimonialCarouselLayout: '',
  testimonialSpotlight: '',
  reviewCard: 'rounded-[8px] bg-white p-4 shadow-[0px_18px_40px_rgba(0,0,0,0.08)] ring-1 ring-black/5',
  reviewList: '',
  reviewListCard: '',
  reviewFormCard: 'border-2 border-black shadow-none',
  reviewForm: '',
  submitBtn: 'h-[40px] w-full rounded-[8px] bg-black text-[10px] font-bold text-white',
  contactFormBtn: 'h-[40px] w-full rounded-[8px] bg-black text-[10px] font-bold text-white',
  cardTitle: 'text-[13px] font-extrabold text-black',
  contactHeading: 'text-[16px] font-extrabold text-black',
  contactListItem: '',
  contactGrid: '',
  contactDetailsWrap: '',
  contactFormWrap: '',
  contactForm: '',
  input:
    'h-[40px] rounded-[6px] border-2 border-black bg-white px-3 text-[12px] outline-none focus:bg-[#ebd96b]/15',
  textarea:
    'min-h-[100px] rounded-[6px] border-2 border-black bg-white px-3 py-2 text-[12px] outline-none focus:bg-[#ebd96b]/15',
  mapContainer: 'mt-6 aspect-[16/9] overflow-hidden rounded-[6px] ring-2 ring-black sm:aspect-[21/9]',
  carouselBtn:
    'grid size-10 place-items-center border-2 border-black bg-white text-lg text-black hover:bg-[#ebd96b]',
  testimonialTitle: 'text-left text-[16px] font-extrabold text-black sm:text-[18px]',
  reviewFormTitle: 'text-[14px] font-extrabold text-black',
  reviewAuthor: 'text-[12px] font-extrabold text-black',
  reviewRatingLabel: 'text-black/50',
  starActive: 'text-black',
  starEmpty: 'text-black/20',
  dateMeta: 'text-[9px] font-bold uppercase tracking-widest text-black/45',
  feedDate: '',
  hoursDay: 'text-black/55',
  hoursValue: 'text-black',
  hoursInner: '',
  avatarRing: 'ring-2 ring-black',
  reviewsGrid: '',
  fabOutline: 'border-2 border-black bg-white text-black',
  fabFill: 'bg-black text-white',
  fabFill2: 'bg-[#ebd96b] text-black',
  fabShell:
    'grid size-12 place-items-center rounded-none text-[18px] shadow-[8px_8px_0_#000] ring-0 sm:size-14',
  fabHint: 'rounded-none bg-[#ebd96b] px-3 py-2 text-[11px] font-bold text-black shadow-[4px_4px_0_#000]',
  mobileNavBg: 'bg-white',
}

export const expandableThemeT5 = {
  maxW: 'max-w-[1020px]',
  stickyHeader: 'bg-white/95 border-b border-black/5 backdrop-blur',
  brandClass: 'text-[12px] font-extrabold text-[#0b1c30]',
  navLink: 'text-[10px] font-semibold text-black/55 hover:text-black',
  loginBtn:
    'hidden h-[32px] items-center justify-center rounded-[10px] border border-[#1b77be]/30 bg-[#eaf2ff] px-4 text-[10px] font-semibold text-[#1b77be] sm:inline-flex',
  signupBtn:
    'hidden h-[32px] items-center justify-center rounded-[10px] bg-[#1b77be] px-4 text-[10px] font-semibold text-white sm:inline-flex',
  sectionTitle: 'text-center text-[14px] font-extrabold text-[#0b1c30]',
  bodyMuted: 'text-[10px] font-medium text-black/45',
  card: 'rounded-[16px] bg-white shadow-[0px_12px_26px_rgba(0,0,0,0.10)] ring-1 ring-black/5',
  altBand: 'bg-[#eaf2ff]',
  offersSection: 'bg-[#eaf2ff]',
  catalogueSection: 'bg-white',
  contactSection: 'bg-white',
  mapSection: 'bg-[#eaf2ff]',
  socialSection: 'bg-[#0b1c30] text-white',
  hoursSection: 'bg-[#f8fbff]',
  testimonialsSection: 'bg-white',
  feedSection: 'bg-[#eaf2ff]',
  offersGrid: '',
  catalogueGrid: '',
  feedGrid: '',
  offerCard: 'ring-1 ring-[#1b77be]/12',
  catalogueCard: '',
  feedCard: 'border border-[#1b77be]/20 bg-white',
  offersTitleExtra: '',
  catalogueTitleExtra: '',
  mapTitleExtra: '',
  feedTitleExtra: '',
  hoursTitleExtra: '',
  testimonialsTitleExtra: '',
  offerTag: 'bg-[#1b77be] text-white',
  priceAccent: 'text-[#1b77be] font-extrabold',
  linkAccent: 'text-[10px] font-bold text-[#1b77be]',
  socialBand: 'bg-[#eaf2ff]',
  socialHeading: 'text-[14px] font-extrabold text-white',
  socialSubtitle: 'text-[10px] font-medium text-white/70',
  socialBtn:
    'rounded-[10px] border border-white/30 bg-[#1b77be]/40 px-4 py-2 text-[10px] font-bold text-white hover:bg-[#1b77be]',
  hoursBand: 'bg-white',
  hoursRow: 'border-[#1b77be]/15',
  hoursList: '',
  testimonialBand: 'bg-[#eaf2ff]',
  testimonialCarouselLayout: '',
  testimonialSpotlight: '',
  reviewCard: 'rounded-[16px] bg-white p-4 shadow-[0px_12px_26px_rgba(0,0,0,0.10)] ring-1 ring-black/5',
  reviewList: '',
  reviewListCard: '',
  reviewFormCard: 'bg-[#f8fbff] ring-1 ring-[#1b77be]/15',
  reviewForm: '',
  submitBtn: 'h-[40px] w-full rounded-[10px] bg-[#1b77be] text-[10px] font-bold text-white',
  contactFormBtn: 'h-[40px] w-full rounded-[10px] bg-[#1b77be] text-[10px] font-bold text-white',
  cardTitle: 'text-[13px] font-extrabold text-[#0b1c30]',
  contactHeading: 'text-[16px] font-extrabold text-[#1b77be]',
  contactListItem: '',
  contactGrid: 'rounded-[16px] bg-[#f8fbff] p-6 ring-1 ring-[#1b77be]/12',
  contactDetailsWrap: '',
  contactFormWrap: '',
  contactForm: '',
  input:
    'h-[40px] rounded-[10px] border border-[#1b77be]/25 bg-[#f8fbff] px-3 text-[12px] outline-none focus:border-[#1b77be]',
  textarea:
    'min-h-[100px] rounded-[10px] border border-[#1b77be]/25 bg-[#f8fbff] px-3 py-2 text-[12px] outline-none focus:border-[#1b77be]',
  mapContainer:
    'mt-6 aspect-[16/9] overflow-hidden rounded-[12px] ring-1 ring-[#1b77be]/25 shadow-[0px_16px_40px_rgba(27,119,190,0.15)] sm:aspect-[21/9]',
  carouselBtn:
    'grid size-10 place-items-center rounded-[10px] border border-[#1b77be]/25 bg-white text-lg text-[#1b77be]',
  testimonialTitle: 'text-left text-[16px] font-extrabold text-[#0b1c30] sm:text-[18px]',
  reviewFormTitle: 'text-[14px] font-extrabold text-[#0b1c30]',
  reviewAuthor: 'text-[12px] font-extrabold text-[#0b1c30]',
  reviewRatingLabel: 'text-[#1b77be]/70',
  starActive: 'text-[#1b77be]',
  starEmpty: 'text-black/15',
  dateMeta: 'text-[9px] font-bold uppercase text-[#1b77be]/65',
  feedDate: '',
  hoursDay: 'text-black/55',
  hoursValue: 'text-[#1b77be]',
  hoursInner: '',
  avatarRing: 'ring-2 ring-[#1b77be]/30',
  reviewsGrid: '',
  fabOutline: 'border-2 border-[#1b77be] bg-white text-[#1b77be]',
  fabFill: 'bg-[#1b77be] text-white',
  fabFill2: 'bg-[#0b1c30] text-white',
  fabShell:
    'grid size-12 place-items-center rounded-[12px] text-[18px] shadow-lg ring-1 ring-[#1b77be]/30 sm:size-14',
  fabHint:
    'rounded-[10px] bg-[#0b1c30] px-3 py-2 text-[11px] font-semibold text-white shadow-lg ring-1 ring-[#1b77be]/40',
  mobileNavBg: 'bg-white',
}

export const expandableThemeT6 = {
  maxW: 'max-w-[980px]',
  stickyHeader: 'bg-[#fbf7f1]/95 border-b border-black/5 backdrop-blur',
  brandClass: 'text-[12px] font-extrabold text-black/80',
  navLink: 'text-[10px] font-semibold text-black/55 hover:text-black',
  loginBtn:
    'hidden h-[32px] items-center justify-center rounded-[999px] border border-black/10 bg-white px-4 text-[10px] font-semibold text-black/70 sm:inline-flex',
  signupBtn:
    'hidden h-[32px] items-center justify-center rounded-[999px] bg-[#b8903a] px-4 text-[10px] font-semibold text-white sm:inline-flex',
  sectionTitle: 'text-center text-[12px] font-extrabold text-[#1a1c19]',
  bodyMuted: 'text-[10px] font-medium text-black/45',
  card: 'rounded-[18px] bg-white shadow-[0px_18px_40px_rgba(0,0,0,0.08)] ring-1 ring-black/5',
  altBand: 'bg-[#fbf7f1]',
  offersSection: 'bg-[#f5ebe0]/55',
  catalogueSection: 'bg-white',
  contactSection: 'bg-[#fbf7f1]',
  mapSection: 'bg-[#ece6dc]',
  socialSection: 'bg-[#4b4b79] text-white',
  hoursSection: 'bg-white',
  testimonialsSection: 'bg-[#ece6dc]/50',
  feedSection: 'bg-[#fbf7f1]',
  offersGrid: '',
  catalogueGrid: '',
  feedGrid: '',
  offerCard: '',
  catalogueCard: '',
  feedCard: 'rounded-[20px]',
  offersTitleExtra: 'tracking-[0.12em] uppercase',
  catalogueTitleExtra: 'tracking-[0.12em] uppercase',
  mapTitleExtra: 'tracking-[0.12em] uppercase',
  feedTitleExtra: 'tracking-[0.12em] uppercase',
  hoursTitleExtra: 'tracking-[0.12em] uppercase',
  testimonialsTitleExtra: 'tracking-[0.12em] uppercase',
  offerTag: 'bg-[#b8903a] text-white',
  priceAccent: 'text-[#b8903a] font-extrabold',
  linkAccent: 'text-[10px] font-bold text-[#b8903a]',
  socialBand: 'bg-[#fbf7f1]',
  socialHeading: 'text-[12px] font-extrabold tracking-[0.18em] text-white uppercase',
  socialSubtitle: 'text-[10px] font-medium text-white/75',
  socialBtn:
    'rounded-full border border-white/35 px-4 py-2 text-[10px] font-semibold text-white hover:bg-[#b8903a]',
  hoursBand: 'bg-white',
  hoursRow: 'border-[#b8903a]/15',
  hoursList: '',
  testimonialBand: 'bg-[#fbf7f1]',
  testimonialCarouselLayout: '',
  testimonialSpotlight: '',
  reviewCard: 'rounded-[18px] bg-white p-4 shadow-[0px_18px_40px_rgba(0,0,0,0.08)] ring-1 ring-black/5',
  reviewList: '',
  reviewListCard: '',
  reviewFormCard: '',
  reviewForm: '',
  submitBtn: 'h-[40px] w-full rounded-[999px] bg-[#b8903a] text-[10px] font-bold text-white',
  contactFormBtn: 'h-[40px] w-full rounded-[999px] bg-[#b8903a] text-[10px] font-bold text-white',
  cardTitle: 'text-[13px] font-extrabold text-[#1a1c19]',
  contactHeading: 'text-[16px] font-extrabold text-[#4b4b79]',
  contactListItem: '',
  contactGrid: '',
  contactDetailsWrap: '',
  contactFormWrap: '',
  contactForm: '',
  input:
    'h-[40px] rounded-full border border-black/10 bg-white px-4 text-[12px] outline-none focus:ring-2 focus:ring-[#b8903a]/25',
  textarea:
    'min-h-[100px] rounded-[20px] border border-black/10 bg-white px-4 py-2 text-[12px] outline-none focus:ring-2 focus:ring-[#b8903a]/25',
  mapContainer:
    'mt-6 aspect-[16/9] overflow-hidden rounded-[20px] ring-1 ring-[#b8903a]/25 sm:aspect-[21/9]',
  carouselBtn:
    'grid size-10 place-items-center rounded-full border border-[#b8903a]/25 bg-white text-lg text-[#b8903a]',
  testimonialTitle: 'text-left text-[16px] font-extrabold text-[#4b4b79] sm:text-[18px]',
  reviewFormTitle: 'text-[14px] font-extrabold text-[#1a1c19]',
  reviewAuthor: 'text-[12px] font-extrabold text-[#1a1c19]',
  reviewRatingLabel: 'text-[#4b4b79]/60',
  starActive: 'text-[#b8903a]',
  starEmpty: 'text-black/15',
  dateMeta: 'text-[9px] font-bold uppercase text-[#4b4b79]/55',
  feedDate: '',
  hoursDay: 'text-black/55',
  hoursValue: 'text-[#b8903a]',
  hoursInner: '',
  avatarRing: 'ring-2 ring-[#4b4b79]/20',
  reviewsGrid: '',
  fabOutline: 'border-2 border-[#b8903a] bg-white text-[#b8903a]',
  fabFill: 'bg-[#b8903a] text-white',
  fabFill2: 'bg-[#4b4b79] text-white',
  fabShell:
    'grid size-12 place-items-center rounded-full text-[18px] shadow-[0px_12px_32px_rgba(75,75,121,0.25)] ring-1 ring-[#b8903a]/30 sm:size-14',
  fabHint:
    'rounded-full bg-white px-4 py-2 text-[11px] font-semibold text-[#4b4b79] shadow-lg ring-1 ring-[#b8903a]/20',
  mobileNavBg: 'bg-[#fbf7f1]',
}

export const expandableThemeT7 = {
  maxW: 'max-w-[1000px]',
  stickyHeader: 'bg-white/95 border-b border-black/5 backdrop-blur',
  brandClass: 'text-[12px] font-extrabold text-[#b40f0f]',
  navLink: 'text-[10px] font-semibold text-black/55 hover:text-black',
  loginBtn:
    'hidden h-[32px] items-center justify-center rounded-[10px] border border-black/10 bg-white px-4 text-[10px] font-semibold text-black/60 sm:inline-flex',
  signupBtn:
    'hidden h-[32px] items-center justify-center rounded-[10px] bg-[#b40f0f] px-4 text-[10px] font-semibold text-white sm:inline-flex',
  sectionTitle: 'text-center text-[14px] font-extrabold text-[#1a1c19]',
  bodyMuted: 'text-[10px] font-medium text-black/45',
  card: 'rounded-[16px] bg-white shadow-[0px_18px_40px_rgba(0,0,0,0.10)] ring-1 ring-black/5',
  altBand: 'bg-[#f7f2ee]',
  offersSection: 'bg-[#f7f2ee]',
  catalogueSection: 'bg-white',
  contactSection: 'bg-[#1a1c19] text-white',
  mapSection: 'bg-[#f7f2ee]',
  socialSection: 'bg-[#b40f0f]/[0.08]',
  hoursSection: 'bg-white',
  testimonialsSection: 'bg-white',
  feedSection: 'bg-[#f7f2ee]',
  offersGrid: '',
  catalogueGrid: '',
  feedGrid: '',
  offerCard: 'ring-1 ring-[#b40f0f]/15',
  catalogueCard: '',
  feedCard: 'border-b-4 border-[#b40f0f]',
  offersTitleExtra: '',
  catalogueTitleExtra: '',
  mapTitleExtra: '',
  feedTitleExtra: '',
  hoursTitleExtra: '',
  testimonialsTitleExtra: '',
  offerTag: 'bg-[#b40f0f] text-white',
  priceAccent: 'text-[#b40f0f] font-extrabold',
  linkAccent: 'text-[10px] font-bold text-[#b40f0f]',
  socialBand: 'bg-[#f7f2ee]',
  socialHeading: 'text-center text-[14px] font-extrabold text-[#1a1c19]',
  socialSubtitle: 'text-[10px] font-medium text-black/45',
  socialBtn:
    'rounded-full border-2 border-[#b40f0f] px-4 py-2 text-[10px] font-bold text-[#b40f0f] hover:bg-[#b40f0f] hover:text-white',
  hoursBand: 'bg-white',
  hoursRow: 'border-black/10',
  hoursList: '',
  testimonialBand: 'bg-[#f7f2ee]',
  testimonialCarouselLayout: '',
  testimonialSpotlight: '',
  reviewCard: 'rounded-[16px] bg-white/90 p-4 shadow-[0px_18px_40px_rgba(0,0,0,0.08)] ring-1 ring-black/5 backdrop-blur',
  reviewList: '',
  reviewListCard: '',
  reviewFormCard: '',
  reviewForm: '',
  submitBtn: 'h-[40px] w-full rounded-[10px] bg-[#b40f0f] text-[10px] font-bold text-white',
  contactFormBtn: 'h-[40px] w-full rounded-[10px] bg-[#b40f0f] text-[10px] font-bold text-white',
  cardTitle: 'text-[13px] font-extrabold text-[#1a1c19]',
  contactHeading: 'text-[16px] font-extrabold text-white',
  contactListItem: 'text-[11px] font-medium text-white/80',
  contactGrid: '',
  contactDetailsWrap: '',
  contactFormWrap: '',
  contactForm: '',
  input:
    'h-[40px] rounded-[10px] border border-white/25 bg-white/10 px-3 text-[12px] text-white outline-none placeholder:text-white/45 focus:ring-2 focus:ring-[#b40f0f]/50',
  textarea:
    'min-h-[100px] rounded-[10px] border border-white/25 bg-white/10 px-3 py-2 text-[12px] text-white outline-none placeholder:text-white/45 focus:ring-2 focus:ring-[#b40f0f]/50',
  mapContainer:
    'mt-6 aspect-[16/9] overflow-hidden rounded-[16px] ring-2 ring-[#b40f0f]/20 shadow-[0px_18px_40px_rgba(180,15,15,0.12)] sm:aspect-[21/9]',
  carouselBtn:
    'grid size-10 place-items-center rounded-[10px] border border-[#b40f0f]/30 bg-white text-lg text-[#b40f0f]',
  testimonialTitle: 'text-left text-[16px] font-extrabold text-[#1a1c19] sm:text-[18px]',
  reviewFormTitle: 'text-[14px] font-extrabold text-[#1a1c19]',
  reviewAuthor: 'text-[12px] font-extrabold text-[#1a1c19]',
  reviewRatingLabel: 'text-black/50',
  starActive: 'text-[#b40f0f]',
  starEmpty: 'text-black/15',
  dateMeta: 'text-[9px] font-bold uppercase text-[#b40f0f]/75',
  feedDate: '',
  hoursDay: 'text-black/55',
  hoursValue: 'text-[#b40f0f]',
  hoursInner: '',
  avatarRing: 'ring-2 ring-[#b40f0f]/35',
  reviewsGrid: '',
  fabOutline: 'border-2 border-[#b40f0f] bg-white text-[#b40f0f]',
  fabFill: 'bg-[#b40f0f] text-white',
  fabFill2: 'bg-black text-white',
  fabShell:
    'grid size-12 place-items-center rounded-[10px] text-[18px] shadow-[0px_12px_28px_rgba(180,15,15,0.35)] ring-1 ring-[#b40f0f]/25 sm:size-14',
  fabHint:
    'rounded-[10px] bg-[#1a1c19] px-3 py-2 text-[11px] font-semibold text-white shadow-lg ring-1 ring-[#b40f0f]/30',
  mobileNavBg: 'bg-white',
}

/** Template 12 — skincare / Flores: cream, brown accents, Playfair brand (nav matches expandable pattern) */
export const expandableThemeT12 = {
  maxW: 'max-w-[1080px]',
  stickyHeader: 'bg-[#FAF8F5]/95 border-b border-black/[0.06] backdrop-blur',
  brandClass: 'truncate font-playfair text-[15px] font-semibold tracking-wide text-[#2C2C2C] sm:text-[17px]',
  navLink: 'text-[10px] font-semibold text-black/45 hover:text-[#6B5344]',
  loginBtn:
    'hidden h-[32px] items-center justify-center rounded-full border border-[#6B5344]/35 bg-white px-4 text-[10px] font-semibold text-[#6B5344] sm:inline-flex',
  signupBtn:
    'hidden h-[32px] items-center justify-center rounded-full bg-[#6B5344] px-4 text-[10px] font-semibold text-white shadow-[0px_8px_20px_rgba(107,83,68,0.2)] sm:inline-flex',
  sectionTitle: 'text-center font-playfair text-[16px] font-semibold text-[#2C2C2C]',
  bodyMuted: 'text-[10px] font-medium text-black/45',
  card: 'rounded-[18px] bg-white shadow-[0px_12px_28px_rgba(107,83,68,0.08)] ring-1 ring-[#6B5344]/10',
  altBand: 'bg-[#FAF8F5]',
  offersSection: 'bg-[#FAF8F5]',
  catalogueSection: 'bg-white',
  contactSection: 'bg-[#F5F0EA]',
  mapSection: 'bg-[#FAF8F5]',
  socialSection: 'bg-[#6B5344]/[0.06]',
  hoursSection: 'bg-white',
  testimonialsSection: 'bg-[#FAF8F5]',
  feedSection: 'bg-white',
  offersGrid: '',
  catalogueGrid: '',
  feedGrid: '',
  offerCard: '',
  catalogueCard: '',
  feedCard: '',
  offersTitleExtra: '',
  catalogueTitleExtra: '',
  mapTitleExtra: '',
  feedTitleExtra: '',
  hoursTitleExtra: '',
  testimonialsTitleExtra: '',
  offerTag: 'bg-[#6B5344] text-white',
  priceAccent: 'text-[#6B5344] font-extrabold',
  linkAccent: 'text-[10px] font-bold text-[#6B5344]',
  socialBand: 'bg-[#FAF8F5]',
  socialHeading: 'text-center font-playfair text-[16px] font-semibold text-[#2C2C2C]',
  socialSubtitle: 'text-[10px] font-medium text-black/45',
  socialBtn:
    'rounded-full border-2 border-[#6B5344] px-4 py-2 text-[10px] font-bold text-[#6B5344] hover:bg-[#6B5344] hover:text-white',
  hoursBand: 'bg-white',
  hoursRow: 'border-[#6B5344]/12',
  hoursList: '',
  testimonialBand: 'bg-[#FAF8F5]',
  testimonialCarouselLayout: '',
  testimonialSpotlight: '',
  reviewCard: 'rounded-[18px] bg-white p-4 shadow-[0px_12px_28px_rgba(107,83,68,0.08)] ring-1 ring-[#6B5344]/10',
  reviewList: '',
  reviewListCard: '',
  reviewFormCard: '',
  reviewForm: '',
  submitBtn: 'h-[40px] w-full rounded-full bg-[#6B5344] text-[10px] font-bold text-white',
  contactFormBtn: 'h-[40px] w-full rounded-full bg-[#6B5344] text-[10px] font-bold text-white',
  cardTitle: 'text-[13px] font-extrabold text-[#2C2C2C]',
  contactHeading: 'text-[16px] font-extrabold text-[#6B5344]',
  contactListItem: '',
  contactGrid: '',
  contactDetailsWrap: '',
  contactFormWrap: '',
  contactForm: '',
  input:
    'h-[40px] rounded-full border border-[#6B5344]/20 bg-white px-4 text-[12px] outline-none focus:ring-2 focus:ring-[#6B5344]/20',
  textarea:
    'min-h-[100px] rounded-[20px] border border-[#6B5344]/20 bg-white px-4 py-2 text-[12px] outline-none focus:ring-2 focus:ring-[#6B5344]/20',
  mapContainer:
    'mt-6 aspect-[16/9] overflow-hidden rounded-[20px] ring-1 ring-[#6B5344]/15 sm:aspect-[21/9]',
  carouselBtn:
    'grid size-10 place-items-center rounded-full border border-[#6B5344]/25 bg-white text-lg text-[#6B5344]',
  testimonialTitle: 'text-left font-playfair text-[17px] font-semibold text-[#2C2C2C] sm:text-[19px]',
  reviewFormTitle: 'font-playfair text-[14px] font-semibold text-[#2C2C2C]',
  reviewAuthor: 'text-[12px] font-extrabold text-[#2C2C2C]',
  reviewRatingLabel: 'text-[#6B5344]/60',
  starActive: 'text-[#6B5344]',
  starEmpty: 'text-black/15',
  dateMeta: 'text-[9px] font-bold uppercase text-[#6B5344]/65',
  feedDate: '',
  hoursDay: 'text-black/55',
  hoursValue: 'text-[#6B5344]',
  hoursInner: '',
  avatarRing: 'ring-2 ring-[#6B5344]/25',
  reviewsGrid: '',
  fabOutline: 'border-2 border-[#6B5344] bg-white text-[#6B5344]',
  fabFill: 'bg-[#6B5344] text-white',
  fabFill2: 'bg-[#2C2C2C] text-white',
  fabShell:
    'grid size-12 place-items-center rounded-full text-[18px] shadow-[0px_12px_28px_rgba(107,83,68,0.25)] ring-1 ring-[#6B5344]/20 sm:size-14',
  fabHint:
    'rounded-full bg-[#FAF8F5] px-4 py-2 text-[11px] font-semibold text-[#2C2C2C] shadow-lg ring-1 ring-[#6B5344]/15',
  mobileNavBg: 'bg-[#FAF8F5]',
}
